[package]
name = "toko-api"
version = "1.0.0"
description = "Toko streaming, torrent, and manga API"

[command]
name = "start"
module = "node"
package = "."
args = ["src/start.js"]

[fs]
"/app" = "./api"